name: run static code analysis
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cppcheck
        run: sudo apt install cppcheck
      - name: Install Vulkan
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          version: latest
      - name: Configure VulkanSceneGraph
        run: cmake -S . -B . -DCMAKE_BUILD_TYPE=Release
      - name: run cppcheck
        run: make -j 2 cppcheck
